review pr
FairlyBet/gaussian_blur_cli pull request #1
Opened 2024-09-23 10:36 UTC by FairlyBet

2024-09-30 07:28 UTC, TheBestTvarynka commented on src/blur_program.rs
> +"#;
😐😐😐

2024-09-30 07:28 UTC, TheBestTvarynka commented on src/blur_program.rs
> +"#;
Is it C++ or something?

2024-09-30 08:48 UTC, FairlyBet commented on src/blur_program.rs
> +"#;
> Is it C++ or something?

it is GLSL. Shading language used by OpenGL and Vulkan.

2024-09-30 09:26 UTC, TheBestTvarynka approved these changes

2024-09-30 15:46 UTC, InAnYan commented on src/main.rs
> +#![deny(clippy::undocumented_unsafe_blocks)]
:fearful:

2024-09-30 17:13 UTC, InAnYan requested changes
Hi! I reviewed your PR and your code made me remember my old good times of learning computer graphics, game development on C with OpenGL and SDL!

Most of my comments are organizational issues, but overall the project is good! Keep up the good work!

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +    let mut paths = vec![];
I think you can refactor the formation of path vector into a separate method, so that `main` would look simple and nice

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +#![deny(clippy::undocumented_unsafe_blocks)]
Probably, they should be documented

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +                        Err(e) => error!("{e}"),
Typically those errors in `Result::Err` are too low-level. So when you want to signal about an error, then a small comment would be nice about "what kind is this error of".

E.g.: `Unable to read directory entry: {e}`. Or something more specific

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +            Err(e) => error!("{e}"),
Besides, I see you used `error!` here, but the program continues to run.

Is it expected behavior? And I think this is some kind of architectural decision, where you have two choices:

1. Proceed: I think it's cool when some things are broken, but there is still some purpose for program to run. But on the other hand, I want to set up the program properly once, and run it only once.

2. Do not proceed: that way you will tell the users that they have a problem in their configuration and they need to fix it. That way I, as a user, would be 100% confident, that when the program is run, it does what I want.

Choose :smile:.

If you chose the first approach, add a message like "Unable to read directory entries, the program will process images only from command line": that way both user and programmer won't be confused.

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +    let config = match Config::new(&args) {
Have you tried using `thiserror` crate?

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +            error!("{e}");
Who knows what kind of error this will be. So I expect something like "Error during loading configuration" (this is bad English).

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +            error!("{e}");
Another thing that caught my eye: you use `error!`, but what if I have set up the logging that way, that it won't display errors or it won't display any kind of logs.

(Or maybe it's not possible to do this?)

I would use `eprintln!` here, because `stderr` is made for this purpose: you can't hide it, and it follows the UNIX philosophy, and how many UNIX programs work.

(*But I think I went into too much detail here*)

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +        _ => error!("Can't create OpenGL context"),
Nice!

However, why `Renderer::new` can't provide a more specific error? 'cause what if there are many reasons of OpenGL context creation failure?

2024-09-30 17:13 UTC, InAnYan commented on src/main.rs
> +pub struct Args {
Is it possible to add new lines after each fields?

That way it's easier to see which `#[...]` correspond to which argument

2024-09-30 17:13 UTC, InAnYan commented on src/shader
> +// This is an example of a shader that might be used
Could you add an extension here? I think there are more-or-less de facto extensions for GLSL: syntax highlighting.

2024-09-30 17:13 UTC, InAnYan commented on src/shader
> +// This is an example of a shader that might be used
Can you also mention: is this your own algorithm or you used some other code?

2024-09-30 17:13 UTC, InAnYan commented on src/shader
> +#version 430 core
(Don't think about this comment too much)

It would be interesting if you could explain, what features make your program uncompatible with lower OpenGL versions? But I went too much in the details.


Just... for me when I was a child, this was a trauma, when I couldn't run a game because it required a bit higher OpenGL version. (But in our modern world, it's becomes irrelevant, event shitty GPUs support latest versions of OpenGL and DirectX)

2024-09-30 17:13 UTC, InAnYan commented on src/shader
> +// This is an example of a shader that might be used
I think name can be changed too

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +        let (mut window, receiver) = glfw.create_window(1, 1, "", WindowMode::Windowed)?;
Huh? Looking through your comment on this PR, I didn't expect it runs any windows. Or maybe I don't understand something?

Now this is looks very interesting!

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +            gl::GetInteger64v(gl::MAX_TEXTURE_BUFFER_SIZE, &mut max_texture_buffer_size);
I wonder, if there are any safe wrappers around OpenGL for Rust...

But it's not a critique, the most important thing is that you hold all the necessary properties

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +        while !images.is_empty() {
What will your program do if the images list is empty?

I think you should add comment for user that the generated list is empty

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +            .ok_or(anyhow!("Cannot create working buffer"))?;
For future, try to experiment with `thiserror`, because I think it's better to use it in future perspective. But for now `anyhow` is okay

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +        images: &mut Vec<Arc<Path>>,
`images` are `mut`?

I guess I'm too biased over functional programming... But it should be okay to use `muts` and iterative algorithms

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +        // This loop tries to load as many images as possible
Truly speaking, I still don't get how the buffers work.

If I have a lot of images: can program process them in chunks? Load N images, process them, free memory, load next N images, process, free memory, and so on.

If the image is too big, can we process it separately? What I mean if we have some images in the buffer and new image doesn't fit: can the program process those small images, and then process the next big one separately?

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +    fn try_load(
I'm not sure if this is an idiomatic way to have methods in `impl`s without `self` (if it's not some kind of constructor).

But this is okay

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +                    _ => unreachable!(),
Huh?

If the variants are exhausted, then there is no need for this line.

If it's not, then maybe you should create a new variant for `LoadError`?

If it's actually unreachable, then could you add a comment there about that? Like you did for `unsafe`?

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +                // converting RGB to RGBA without setting the Alpha
That's cool

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +#[derive(Debug)]
That's the perfect place to use `thiserror` :smile:

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
> +        if let Ok(path) = env::var("GBLUR") {
As you know: "do not use magic numbers/strings". Introduce a constant)

2024-09-30 17:13 UTC, InAnYan commented on src/blur_program.rs
> +            gl::GetProgramiv(program, gl::LINK_STATUS, &mut is_linked);
Ah, old good times of OpenGL and C. Mmm, such a nostalgia to read these low-level commands

2024-09-30 17:13 UTC, InAnYan commented on src/blur_program.rs
> +            gl::GetProgramiv(program, gl::LINK_STATUS, &mut is_linked);
But still. Maybe it would be more rational to use a safe wrapper over OpenGL?

2024-09-30 17:13 UTC, InAnYan commented on src/blur_program.rs
> +            assert_ne!(direction_location, -1);
What is it doing here? On which condition this happens?

If it sometimes can be violated, then, make an error type.

Yeah, it's tedious to make error types for every exceptional situation, but with `thiserror` this is very easy

2024-09-30 17:13 UTC, InAnYan commented on src/blur_program.rs
> +uniform ivec2 direction;
I highly suggest using a template engine here.

It will be easier to manage the shader file.

I highly highly recommend you to try out [askama](https://github.com/djc/askama).

It is a very simple template engine with **type safety** and it's fully enough for your needs

2024-09-30 17:13 UTC, InAnYan commented on src/buffer.rs
Name should be "buffers".

What do you think of separating all of the `struct`s and their respective `impl`s into different modules? That way it's easier to navigate the code and find relevant `struct`s

2024-09-30 17:13 UTC, InAnYan commented on src/blur.rs
I think you should work on splitting this file into separate modules.

Why it's `blur.rs` and not a `renderer.rs`, etc.

2024-09-30 17:15 UTC, InAnYan commented on src/main.rs
> +#![deny(clippy::undocumented_unsafe_blocks)]
I saw you actually made a lot of comments, but why this `deny` is still needed...

2024-09-30 17:21 UTC, FairlyBet commented on src/main.rs
> +#![deny(clippy::undocumented_unsafe_blocks)]
`#![deny(clippy::undocumented_unsafe_blocks)]` means that if there is an undocumented unsafe block then the project does not compile. It would allow them if it was `#![allow(clippy::undocumented_unsafe_blocks)]`.

2024-10-02 08:47 UTC, FairlyBet commented on src/main.rs
> +    let config = match Config::new(&args) {
No, i've never heard of it.

2024-10-02 08:57 UTC, FairlyBet commented on src/shader
> +// This is an example of a shader that might be used
There is a standard way to do gaussian bluring. The link to wiki is in PR description.

2024-10-02 08:58 UTC, FairlyBet commented on src/blur.rs
> +        let (mut window, receiver) = glfw.create_window(1, 1, "", WindowMode::Windowed)?;
This is the easiest way to create opengl context. There is also `Visible(false)` flag specificaly for this case.

2024-10-02 09:00 UTC, FairlyBet commented on src/blur.rs
> +        while !images.is_empty() {
If the list is empty then no job is done and the program ends. There are scenarios when user want to just check limitations without any additional prints.

2024-10-02 09:01 UTC, FairlyBet commented on src/blur.rs
> +        images: &mut Vec<Arc<Path>>,
The implementation requires to remove images that go into processing or that can't be processed from this vec.

2024-10-02 09:03 UTC, FairlyBet commented on src/blur.rs
> +        // This loop tries to load as many images as possible
Processing images in chunks is quite complicated and out of frame time of this project, so as described in PR description if image's size is too big to fit into the **entire** buffer then the error is printed and image is skipped, otherwise all images are processed.

2024-10-02 09:04 UTC, FairlyBet commented on src/blur.rs
> +                    _ => unreachable!(),
It is actualy unreachable in current implementation

2024-10-02 09:06 UTC, FairlyBet commented on src/blur_program.rs
> +            gl::GetProgramiv(program, gl::LINK_STATUS, &mut is_linked);
Using safe wrapper is out of timeframe of this project as i am not familiar with any and they require some time to study.

2024-10-02 09:08 UTC, FairlyBet commented on src/blur_program.rs
> +            assert_ne!(direction_location, -1);
This should never panic but still it presents for some kind of guarantee. If it panics then the program contains syntax error that should be eliminated. This is not what user should deal with and not what really should ever happen, but just in case.

2024-10-02 09:09 UTC, FairlyBet commented on src/blur_program.rs
> +uniform ivec2 direction;
Very good but still, timeframe of project is 3 days so maybe another time.

2024-10-02 09:14 UTC, FairlyBet commented on src/shader
> +#version 430 core
Persitent mapping is why reuired version is 4.4

2024-10-02 09:14 UTC, FairlyBet commented on src/shader
> +#version 430 core
It is described in PR

2024-10-02 09:16 UTC, FairlyBet commented on src/main.rs
> +        _ => error!("Can't create OpenGL context"),
Unfortunately, it can't provide more specific reason.

2024-10-02 10:40 UTC, FairlyBet commented on src/main.rs
> +            error!("{e}");
Changed it so `error!` output goes into stderr

2024-10-02 10:51 UTC, FairlyBet commented on src/buffer.rs
Okay

2024-10-02 11:00 UTC, FairlyBet commented on src/blur.rs
Okay

2024-10-02 11:37 UTC, FairlyBet commented on src/main.rs
> +            error!("{e}");
> Another thing that caught my eye: you use `error!`, but what if I have set up the logging that way, that it won't display errors or it won't display any kind of logs.
this is the point of using `trace` so that it can be configured in many ways. if a user doesn't want any logging then he may get that behaviour.

2024-10-02 11:40 UTC, jiztastamablastamarang approved these changes

2024-10-02 11:42 UTC, FairlyBet commented
> Hi! I reviewed your PR and your code made me remember my old good times of learning computer graphics, game development on C with OpenGL and SDL!
> 
> Most of my comments are organizational issues, but overall the project is good! Keep up the good work!

Hey, i tried to reply on most of your comments and implemented some of your propositions. Unfortunately i don't have much time at the moment to dedicate for some interesting ideas (like using safe opengl wrapper), so, If you don't mind, can you approve it? :)

2024-10-02 13:24 UTC, Citizen4our approved these changes
Approved. But I'm not sure if unsafe can be used in a capstone project

2024-10-02 14:14 UTC, FairlyBet commented
> Approved. But I'm not sure if unsafe can be used in a capstone project

It can be used if documented.

2024-10-02 17:15 UTC, InAnYan commented
@FairlyBet I need to aprove it?

Sure, sure, thanks for the comments, you are right, you code is 100% for the capstone and dedicated time

2024-10-02 17:16 UTC, InAnYan approved these changes

2024-10-03 16:57 UTC, FairlyBet commented
@JekiXD Hi, this is my capstone project. Today is deadline, but no one from rust forum approved it. Can you please approve it as forum member? 🙏 [link](https://users.rust-lang.org/t/rust-bootcamp-project-review/119103?u=fairlybet)

2024-10-03 17:05 UTC, JekiXD approved these changes
LGTM

2024-10-03 19:18 UTC, khomiakmaxim approved these changes
The project looks good. It is really easy to tell that the author spent a lot of effort into it.
As a minor note, I would advise creating the output directory automatically when the 
`-o` option was passed, if it wasn't already present.

2024-10-04 08:00 UTC, FairlyBet commented
> The project looks good. It is really easy to tell that the author spent a lot of effort into it. As a minor note, I would advise creating the output directory automatically when the  `-o` option was passed, if it wasn't already present.

Oh, it's a good advise I didn't think of. I will surely implement it. Thanks again for your review.

2024-10-14 16:38 UTC, merged